config/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path, include
from users.apps import UsersConfig
from users.views import UserListView
from django.contrib import admin
from rest_framework_simplejwt.views import TokenRefreshView

from users.views import \
    LoginAPIView, \
    UserCreateAPIView, \
    UserRetrieveUpdateDestroyAPIView, \
    UserProfile

app_name = UsersConfig.name

urlpatterns = \
    [
        path('admin/', admin.site.urls),
        path('auth/', include('django.contrib.auth.urls')),
        path('logout/', LogoutView.as_view(), name='logout'),
        path('accounts/login/', LoginView.as_view(), name='login'),
        path('', UserListView.as_view(), name='users_list'),
    ] + \
    [
        path('api/token/',
             LoginAPIView.as_view(),
             name='token_obtain_pair'),

        path('api/registration/',
             UserCreateAPIView.as_view(),
             name='user_registration'),

        path('api/user/<int:pk>/',
             UserRetrieveUpdateDestroyAPIView.as_view(),
             name='user'),

        path('api/user/profile/<int:pk>/',
             UserProfile.as_view(),
             name='user_profile'),
    ]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.base_user import BaseUserManager

NULLABLE = {'null': True, 'blank': True}


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Users require an email field')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    username = None
    name = models.CharField(unique=False, max_length=100, verbose_name='name', **NULLABLE)
    email = models.EmailField(unique=True, verbose_name='email')
    birthday = models.DateField(verbose_name='Birthday', **NULLABLE)
    friend = models.ManyToManyField('User', verbose_name='Friends', blank=True)

    def display_friends(self):
        friends_list = User.objects.values_list('friend', flat=True).filter(pk=self.pk)
        return ', '.join([str(x) for x in friends_list])

    def __str__(self):
        return f'{self.email}'

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'User'
        verbose_name_plural = 'Users'

users/views.py
from rest_framework import status
from rest_framework.exceptions import ValidationError
from rest_framework.generics import CreateAPIView, RetrieveUpdateDestroyAPIView, GenericAPIView, ListAPIView
from rest_framework.permissions import AllowAny
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework_simplejwt.exceptions import TokenError, InvalidToken
from rest_framework_simplejwt.views import TokenObtainPairView

from django.views.generic import ListView
from users.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from users.serializers import UserSerializer
from users.permissions import IsOwner, IsProfileOwner


class UserListView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'users/users_list.html'
    ordering = 'email'


class UserCreateAPIView(CreateAPIView):
    """New user creation"""

    serializer_class = UserSerializer
    permission_classes = [AllowAny]

    def perform_create(self, serializer):
        """Set password as hash """

        # user = super().perform_create(serializer)
        user = serializer.save()

        if user is not None:
            password = self.request.data['password']
            user.set_password(password)
            user.save()
        return user


class LoginAPIView(TokenObtainPairView):
    """Authentication with token"""
    def post(self, request: Request, *args, **kwargs) -> Response:
        serializer = self.get_serializer(data=request.data)

        try:
            serializer.is_valid(raise_exception=True)
        except TokenError as e:
            raise InvalidToken(e.args[0])

        return Response(serializer.validated_data, status=status.HTTP_200_OK)


class UserRetrieveUpdateDestroyAPIView(RetrieveUpdateDestroyAPIView):

    serializer_class = UserSerializer
    permission_classes = [IsOwner]
    queryset = User.objects.all()

    def patch(self, request, *args, **kwargs):
        pk = self.kwargs.get('pk')
        user = User.objects.get(pk=pk)
        serializer = UserSerializer(user, data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()

        return Response(
            data=serializer.data,
            status=status.HTTP_200_OK
        )


class UserProfile(ListAPIView):
    permission_classes = [IsProfileOwner]
    serializer_class = UserSerializer

    def get(self, request, *args, **kwargs):
        print(f"{request = }")
        print(f"{args = }")
        print(f"{kwargs = }")
        pk = self.kwargs.get("pk")
        friends_emails = User.objects.values_list('email', flat=True).filter(friend__pk=pk)
        print(friends_emails)
        data = {'friends_emails': ', '.join(friends_emails)}
        print(data)
        return Response(data=friends_emails, status=200)

users/templates/users/base.html
{% load static %}
<html lang="en">
<head>
    <title>{{ title }}</title>
</head>

<body>

<header>
    <div class="bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
            {% include 'users/includes/inc_main_menu.html' %}
            </div>
        </div>
</header>

<main role="main">


    <div class="album py-5 bg-light">
        <div class="container">

            <div class="row">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

</main>


</body>
</html>

users/templates/users/includes/inc_main_menu.html
<header>
    <main></main>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'users:users_list' %}">
            <span class="navbar-text">HAPPY BIRTHDAY</span>
            {% if user.is_authenticated %}
            <a href="{% url 'users:users_list' %}" class="btn btn-outline-secondary mr-2" type="button">Пользователи</a>
            {% endif %}

            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        {% if user.is_authenticated %}

                        <form method="post" action="{% url 'users:logout' %}?next={{ 'users:login' }}">
                            {% csrf_token %}
                            <button type="submit">logout</button>
                        </form>

                    </li>
                    <li>
                        {% else %}
                        <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                        {% endif %}
                    </li>
                    {% if not user.is_authenticated %}
                    <li class="nav-item active">
                    </li>
                    {%endif%}
                </ul>

            </div>
    </nav>

</header>

users/templates/users/users_list.html
{% extends 'users/base.html' %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 order-md-1">
        <h5 class="mb-3 text-center">Пользователи</h5>

        <div class="container mt-5">

            {% for object in object_list %}
            <div class="card mb-3">
                <div class="card-body">
                    <h4 class="card-title">{{ object.email }}</h4>
                    <p class="card-text">Имя: {{ object.name }}</p>

                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</div>

    <body>
      {{user}} authentication:
      {{user.is_authenticated}}

    </body>
{% endblock %}